const DEFAULT_PRODUCTS = [
{id:'v150',name:'Valorant 150 VP',category:'valorant',categoryName:'Valorant',price:75,image:'150vp.jpg',stock:18,badge:'Başlangıç'},
{id:'v600',name:'Valorant 600 VP',category:'valorant',categoryName:'Valorant',price:175,image:'600vp.jpg',stock:12,badge:'Popüler'},
{id:'v1200',name:'Valorant 1200 VP',category:'valorant',categoryName:'Valorant',price:275,image:'1200vp.jpg',stock:10,badge:'Önerilen'},
{id:'v2200',name:'Valorant 2200 VP',category:'valorant',categoryName:'Valorant',price:450,image:'2200vp.jpg',stock:8,badge:'Avantajlı'},
{id:'v3500',name:'Valorant 3500 VP',category:'valorant',categoryName:'Valorant',price:650,image:'3500vp.jpg',stock:5},
{id:'v7300',name:'Valorant 7300 VP',category:'valorant',categoryName:'Valorant',price:1200,image:'7300vp.jpg',stock:3},
{id:'lol210',name:'LoL 210 RP',category:'lol',categoryName:'League of Legends',price:75,image:'210 rp lol.jpg',stock:16},
{id:'lol850',name:'LoL 850 RP',category:'lol',categoryName:'League of Legends',price:220,image:'850 rp lol.jpg',stock:14,badge:'Popüler'},
{id:'lol1675',name:'LoL 1675 RP',category:'lol',categoryName:'League of Legends',price:390,image:'1675 rp lol.jpg',stock:9},
{id:'lol3125',name:'LoL 3125 RP',category:'lol',categoryName:'League of Legends',price:690,image:'3125 rp lol.jpg',stock:6},
{id:'gift25',name:'25 TL Hediye Kartı',category:'gift',categoryName:'Hediye Kartı',price:25,image:'hediyekartı25.jpg',stock:30},
{id:'gift100',name:'100 TL Hediye Kartı',category:'gift',categoryName:'Hediye Kartı',price:100,image:'hediyekartı100.jpg',stock:21,badge:'Hızlı'},
{id:'gift250',name:'250 TL Hediye Kartı',category:'gift',categoryName:'Hediye Kartı',price:250,image:'hediyekartı250.jpg',stock:12},
{id:'gift500',name:'500 TL Hediye Kartı',category:'gift',categoryName:'Hediye Kartı',price:500,image:'hediyekartı500.jpg',stock:7},
{id:'steamkey',name:'Steam Random Key',category:'steam',categoryName:'Steam',price:79,image:'steam random key.jpg',stock:24,badge:'Sürpriz'},
{id:'play100',name:'Google Play 100 TL',category:'playstore',categoryName:'Google Play',price:100,image:'100tl.jpg',stock:10},
{id:'xbox',name:'Xbox Gift Card',category:'xbox',categoryName:'Xbox',price:250,image:'xbox.jpg',stock:8},
{id:'pubg',name:'PUBG Mobile Paket',category:'pubg',categoryName:'PUBG Mobile',price:199,image:'pugb-mobile.jpg',stock:11}
];
const CATEGORIES=[
{id:'valorant',name:'Valorant',image:'valorant.jpg',sub:'VP paketleri'},
{id:'lol',name:'League of Legends',image:'lol kategori foto.jpg',sub:'RP paketleri'},
{id:'steam',name:'Steam',image:'steam.jpg',sub:'Kod ve oyun anahtarları'},
{id:'pubg',name:'PUBG Mobile',image:'pugb-mobile.jpg',sub:'Mobil oyun paketleri'},
{id:'xbox',name:'Xbox',image:'xbox.jpg',sub:'Hediye kartları'},
{id:'gift',name:'Hediye Kartları',image:'hediyekartı.jpg',sub:'Dijital bakiye kartları'}
];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(v);
const storage={get(k,f){try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
function initData(){if(!localStorage.getItem('xoProducts'))storage.set('xoProducts',DEFAULT_PRODUCTS);if(!localStorage.getItem('xoUsers'))storage.set('xoUsers',[{id:'u-demo',name:'Demo Kullanıcı',email:'demo@xoepin.com',password:'123456'}]);if(!localStorage.getItem('xoOrders'))storage.set('xoOrders',[]);if(!localStorage.getItem('xoCart'))storage.set('xoCart',[])}
function products(){return storage.get('xoProducts',DEFAULT_PRODUCTS)} function cart(){return storage.get('xoCart',[])} function orders(){return storage.get('xoOrders',[])} function user(){return storage.get('xoSession',null)}
function showToast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2200)}
function updateAccountLink(){const a=$('#accountLink');if(!a)return;const u=user();if(u){a.href='account.html';a.querySelector('b').textContent=u.name.split(' ')[0]}else a.querySelector('b').textContent='Hesabım'}
let activeCategory='all', searchTerm='';
function renderCategories(){const el=$('#categoryGrid');if(!el)return;el.innerHTML=CATEGORIES.map(c=>`<article class="category-card" data-category="${c.id}"><img src="${c.image}" alt="${c.name}"><h3>${c.name}</h3><small>${c.sub}</small></article>`).join('');$$('[data-category]',el).forEach(x=>x.onclick=()=>{activeCategory=x.dataset.category;const f=$('#categoryFilter');if(f)f.value=activeCategory;renderProducts();$('#urunler')?.scrollIntoView({behavior:'smooth'})})}
function initFilters(){const f=$('#categoryFilter');if(!f)return;CATEGORIES.forEach(c=>f.insertAdjacentHTML('beforeend',`<option value="${c.id}">${c.name}</option>`));f.onchange=()=>{activeCategory=f.value;renderProducts()};$('#sortSelect').onchange=renderProducts}
function filteredProducts(){let list=products().filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(!searchTerm||`${p.name} ${p.categoryName}`.toLowerCase().includes(searchTerm)));const sort=$('#sortSelect')?.value;if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);return list}
function renderProducts(){const grid=$('#productGrid');if(!grid)return;const list=filteredProducts();$('#emptyState').hidden=!!list.length;grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-media"><img src="${p.image}" alt="${p.name}">${p.badge?`<span class="badge">${p.badge}</span>`:''}<span class="delivery-badge">${p.stock>0?'⚡ STOKTA':'TÜKENDİ'}</span></div><div class="product-body"><span class="product-category">${p.categoryName}</span><h3 class="product-title">${p.name}</h3><p class="product-desc">Demo stok: <b>${p.stock}</b></p><div class="product-bottom"><div class="price"><strong>${money(p.price)}</strong><small>KDV dahil • demo</small></div><button class="add-cart" data-add="${p.id}" ${p.stock<1?'disabled':''}>＋</button></div></div></article>`).join('');$$('[data-add]',grid).forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function addToCart(id){const ps=products(),p=ps.find(x=>x.id===id);let c=cart();const found=c.find(i=>i.id===id),qty=found?found.qty:0;if(!p||p.stock<=qty)return showToast('Bu ürün için yeterli demo stok yok.');if(found)found.qty++;else c.push({id,qty:1});storage.set('xoCart',c);renderCart();showToast('Sepete eklendi ✓')}
function changeQty(id,d){let c=cart();const item=c.find(i=>i.id===id),p=products().find(x=>x.id===id);if(!item)return;if(d>0&&item.qty>=p.stock)return showToast('Stok sınırına ulaştın.');item.qty+=d;if(item.qty<=0)c=c.filter(x=>x.id!==id);storage.set('xoCart',c);renderCart()}
function renderCart(){const c=cart(),ps=products();$('#cartBadge')&&($('#cartBadge').textContent=c.reduce((s,i)=>s+i.qty,0));const items=$('#cartItems');if(!items)return;const empty=$('#cartEmpty'),footer=$('#cartFooter');if(!c.length){items.innerHTML='';empty.hidden=false;footer.hidden=true;return}empty.hidden=true;footer.hidden=false;let total=0;items.innerHTML=c.map(i=>{const p=ps.find(x=>x.id===i.id);if(!p)return'';total+=p.price*i.qty;return `<div class="cart-item"><img src="${p.image}"><div><b>${p.name}</b><small>${money(p.price)} / adet</small><div class="cart-item-actions"><button data-minus="${p.id}">−</button><small>${i.qty} adet</small><button data-plus="${p.id}">+</button><button class="cart-remove" data-remove="${p.id}">Sil</button></div></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('');$('#cartTotal').textContent=money(total);$$('[data-minus]',items).forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]',items).forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));$$('[data-remove]',items).forEach(b=>b.onclick=()=>{storage.set('xoCart',c.filter(x=>x.id!==b.dataset.remove));renderCart()})}
function setupDrawer(){$('#openCart')?.addEventListener('click',()=>{$('#cartDrawer').classList.add('open');document.body.classList.add('no-scroll')});const close=()=>{$('#cartDrawer')?.classList.remove('open');document.body.classList.remove('no-scroll')};$('#closeCart')?.addEventListener('click',close);$('#cartBackdrop')?.addEventListener('click',close);$('#checkoutBtn')?.addEventListener('click',()=>{if(!cart().length)return;if(!user()){sessionStorage.setItem('xoAfterLogin','checkout.html');location.href='login.html';return}location.href='checkout.html'})}
function setupSearch(){const input=$('#searchInput'),panel=$('#searchPanel');if(!input)return;input.oninput=()=>{searchTerm=input.value.trim().toLowerCase();renderProducts();if(!searchTerm){panel.hidden=true;return}const m=products().filter(p=>p.name.toLowerCase().includes(searchTerm)).slice(0,5);panel.innerHTML=m.map(p=>`<button type="button" class="search-result" data-result="${p.id}"><img src="${p.image}"><span><b>${p.name}</b><small>${money(p.price)} • stok ${p.stock}</small></span></button>`).join('')||'<div class="search-result"><span>Sonuç bulunamadı</span></div>';panel.hidden=false;$$('[data-result]',panel).forEach(b=>b.onclick=()=>{input.value=products().find(p=>p.id===b.dataset.result).name;searchTerm=input.value.toLowerCase();panel.hidden=true;renderProducts()})};$('#searchForm')?.addEventListener('submit',e=>e.preventDefault())}
function setupMenu(){const b=$('#mobileMenu'),n=$('#mainNav');if(b)b.onclick=()=>n.classList.toggle('open')}
function loginPage(){const form=$('#loginForm');if(!form)return;$('#demoLogin').onclick=()=>{$('#loginEmail').value='demo@xoepin.com';$('#loginPassword').value='123456';form.requestSubmit()};form.onsubmit=e=>{e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),pass=$('#loginPassword').value;const u=storage.get('xoUsers',[]).find(x=>x.email===email&&x.password===pass);if(!u)return showToast('E-posta veya şifre hatalı.');storage.set('xoSession',{id:u.id,name:u.name,email:u.email});showToast('Giriş başarılı ✓');setTimeout(()=>{location.href=sessionStorage.getItem('xoAfterLogin')||'account.html';sessionStorage.removeItem('xoAfterLogin')},500)}}
function registerPage(){const form=$('#registerForm');if(!form)return;form.onsubmit=e=>{e.preventDefault();const name=$('#regName').value.trim(),email=$('#regEmail').value.trim().toLowerCase(),password=$('#regPassword').value;const users=storage.get('xoUsers',[]);if(users.some(u=>u.email===email))return showToast('Bu e-posta zaten kayıtlı.');const u={id:'u-'+Date.now(),name,email,password};users.push(u);storage.set('xoUsers',users);storage.set('xoSession',{id:u.id,name,email});showToast('Demo hesabın oluşturuldu ✓');setTimeout(()=>location.href='index.html',500)}}
function checkoutPage(){const form=$('#checkoutForm');if(!form)return;const u=user();if(!u){sessionStorage.setItem('xoAfterLogin','checkout.html');location.href='login.html';return}$('#checkoutName').value=u.name;$('#checkoutEmail').value=u.email;const c=cart(),ps=products();if(!c.length){location.href='index.html';return}let total=0;$('#checkoutItems').innerHTML=c.map(i=>{const p=ps.find(x=>x.id===i.id);total+=p.price*i.qty;return `<div class="summary-item"><span>${p.name} × ${i.qty}</span><b>${money(p.price*i.qty)}</b></div>`}).join('');$('#checkoutTotal').textContent=money(total);$('#cardNumber').oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,16);e.target.value=v.replace(/(.{4})/g,'$1 ').trim()};form.onsubmit=e=>{e.preventDefault();const fresh=products();for(const i of c){const p=fresh.find(x=>x.id===i.id);if(!p||p.stock<i.qty)return showToast(`${p?.name||'Ürün'} stokta yetersiz.`)}for(const i of c){fresh.find(x=>x.id===i.id).stock-=i.qty}storage.set('xoProducts',fresh);const id='XO-'+Date.now().toString().slice(-8);const codes=[];c.forEach(i=>{const p=fresh.find(x=>x.id===i.id);for(let n=0;n<i.qty;n++)codes.push({product:p.name,code:`DEMO-${p.id.toUpperCase()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`})});const all=orders();all.unshift({id,date:new Date().toISOString(),userId:u.id,email:u.email,name:$('#checkoutName').value,total,status:'Teslim edildi',items:c.map(i=>({id:i.id,qty:i.qty,name:fresh.find(x=>x.id===i.id).name,price:fresh.find(x=>x.id===i.id).price})),codes});storage.set('xoOrders',all);storage.set('xoCart',[]);showToast('Demo ödeme başarılı ✓');setTimeout(()=>location.href='account.html?new='+encodeURIComponent(id),700)}}
function accountPage(){const list=$('#ordersList');if(!list)return;const u=user();if(!u){sessionStorage.setItem('xoAfterLogin','account.html');location.href='login.html';return}$('#accountTitle').textContent=`Merhaba, ${u.name}`;$('#accountSubtitle').textContent=u.email;$('#logoutBtn').onclick=()=>{localStorage.removeItem('xoSession');location.href='index.html'};const mine=orders().filter(o=>o.userId===u.id||o.email===u.email);if(!mine.length){list.innerHTML='<div class="empty-panel"><span>📦</span><h3>Henüz siparişin yok</h3><p>Demo sipariş oluşturarak bu ekranı test edebilirsin.</p><a class="btn btn-primary" href="index.html#urunler">Ürünlere Git</a></div>';return}list.innerHTML=mine.map(o=>`<article class="order-card"><div class="order-top"><div><small>SİPARİŞ NO</small><b>${o.id}</b></div><span class="status-pill">✓ ${o.status}</span></div><div class="order-meta"><span>${new Date(o.date).toLocaleString('tr-TR')}</span><strong>${money(o.total)}</strong></div><div class="order-products">${o.items.map(i=>`<div>${i.name} × ${i.qty}</div>`).join('')}</div><div class="codes"><h4>Demo E-Pin Kodları</h4>${o.codes.map(c=>`<div class="code-row"><span>${c.product}</span><code>${c.code}</code><button data-copy="${c.code}">Kopyala</button></div>`).join('')}</div></article>`).join('');$$('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);showToast('Kod kopyalandı ✓')}catch{showToast(b.dataset.copy)}})}
function adminPage(){const tbody=$('#adminProducts');if(!tbody)return;const render=()=>{const ps=products(),os=orders();const revenue=os.reduce((s,o)=>s+o.total,0),units=ps.reduce((s,p)=>s+p.stock,0);$('#adminStats').innerHTML=`<article><small>TOPLAM SİPARİŞ</small><strong>${os.length}</strong></article><article><small>DEMO CİRO</small><strong>${money(revenue)}</strong></article><article><small>KALAN STOK</small><strong>${units}</strong></article><article><small>ÜRÜN SAYISI</small><strong>${ps.length}</strong></article>`;tbody.innerHTML=ps.map(p=>`<tr><td><div class="table-product"><img src="${p.image}"><span><b>${p.name}</b><small>${p.categoryName}</small></span></div></td><td>${money(p.price)}</td><td><input class="stock-input" type="number" min="0" value="${p.stock}" data-stock="${p.id}"></td><td><button class="mini-btn" data-save="${p.id}">Kaydet</button></td></tr>`).join('');$$('[data-save]').forEach(b=>b.onclick=()=>{const ps2=products(),p=ps2.find(x=>x.id===b.dataset.save);p.stock=Math.max(0,Number($(`[data-stock="${p.id}"]`).value)||0);storage.set('xoProducts',ps2);showToast('Stok güncellendi ✓');render()});const holder=$('#adminOrders');holder.innerHTML=os.length?os.map(o=>`<article class="order-card compact"><div class="order-top"><div><small>${o.id}</small><b>${o.name}</b></div><span class="status-pill">${o.status}</span></div><div class="order-meta"><span>${o.email} • ${new Date(o.date).toLocaleString('tr-TR')}</span><strong>${money(o.total)}</strong></div></article>`).join(''):'<div class="empty-panel"><p>Henüz demo sipariş yok.</p></div>'};render();$('#resetDemo').onclick=()=>{if(confirm('Tüm demo hesap, sipariş, sepet ve stok verileri sıfırlansın mı?')){['xoProducts','xoUsers','xoOrders','xoCart','xoSession'].forEach(k=>localStorage.removeItem(k));initData();showToast('Demo verileri sıfırlandı.');setTimeout(()=>location.reload(),400)}}}
document.addEventListener('DOMContentLoaded',()=>{initData();updateAccountLink();renderCategories();initFilters();renderProducts();renderCart();setupDrawer();setupSearch();setupMenu();loginPage();registerPage();checkoutPage();accountPage();adminPage()});
